### ISSUE TITLE
Fix nested containers/use bootstrap grid

### ISSUE THREAD

**Issue by ericmbarnard** [parkland-AMP/amp-website#18]
@Tykki @JdGXII 

I'm looking at chunks of HTML like this: 
https://github.com/parkland-AMP/amp-website/blob/master/index.html#L17-L22

Typically, when you start a new row, you need to define how many columns you want to the content to take:
```
<div class="row">
    <div class="col-md-12">
        ... content here
    </div>
</div>
```
This allows us to use the `col-md-XX`,  `col-sm-XX`, etc... to adjust for devices. Without those the layout becomes pretty difficult to wrangle. 

Also, it appears that in some places you have a `container` with a nested `fluid-container` inside of it. Not sure if that's your intention, but I imagine it might be causing some layout headaches

**Comment by Tykki** [comment]
Actually the "row" class there is used solely for the inline/block formatting for the icons to sit in a row above the navbar. I can add a col-md-xx child class also but although the grid is not needed for that simple type formatting. For the nested containers, those are needed because in bootstrap nesting normal containers normal containers breaks the layout at certain points. If a nested container class is needed most times you will use "container-fluid" for the nested class so to avoid content coming out of margins.
