### ISSUE TITLE
Links - do we need angular here?

### ISSUE THREAD

**Issue by ericmbarnard** [parkland-AMP/amp-website#19]
@Tykki @JdGXII 

I'm looking at this: 
https://github.com/parkland-AMP/amp-website/blob/master/index.html#L17-L22

and 
https://github.com/parkland-AMP/amp-website/blob/master/index.html#L41-L43

Do we need angular here? I'm just asking from a maintainability perspective. If you're trying to get a cool bouncing/scroll animation going, then that's cool. I'm just wondering if we can use old-fashioned anchor tags here instead? 
https://perishablepress.com/ids-are-anchors-too/

**Comment by Tykki** [comment]
Right now the main reason Angular is enabled on the site is for the modal content in the nav bar (join us/contact us) without angular managing modals are a serious pain but possible. The anchor tags using the angular expressions are necessary because of the "#" in the url that appears when Angularjs is invoked on a page, normal anchor tags do not register due to the hashtag not being read property or being skipped over.

**Comment by Tykki** [comment]
Jose solved our issue here
